---
- hosts: node
  remote_user: root
  become: yes
  tasks:
  - name: detect registry ip
    shell: docker inspect --format "{{ '{{' }}(index .IPAM.Config 0).Gateway{{ '}}' }}" bridge
    register: registry_ip

  - name: store registry ip
    copy:
      dest: /opt/control/registry_ip
      content: "{{ registry_ip.stdout }}"
    delegate_to: localhost
