---
- hosts: node
  remote_user: root
  become: yes
  tasks:
  - name: clean up dev-env repository path
    file:
      path: /opt/control/contrail-dev-env
      state: absent

  - name: install git package
    package:
      name: git
      state: present

  - name: clone dev-env repository
    git:
      repo: https://github.com/progmaticlab/contrail-dev-env.git
      dest: /root/contrail-dev-env

  - name: HACK format /etc/docker/daemon.json to make happy contrail-container-deployeer
    copy:
      src: /opt/control/daemon.json.tmpl
      dest: /root/contrail-dev-env/daemon.json.tmpl
